baseURL = "https://guides.prestigelogic.com"
languageCode = "en-us"
title = "Prestige Logic Guides"
theme = "hugo-theme-learn"

author = "Prestige Logic"
# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

enableEmoji = true

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"